repos:
    - repo: https://github.com/jazzband/pip-tools
      rev: 6.0.1
      hooks:
        - id: pip-compile
        - id: pip-compile
          name: pip-compile dev
          args: [dev-requirements.in]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/psf/black
      rev: 20.8b1
      hooks:
          - id: black
